development:
  clients:
    default:
      uri: "<%= ENV['MONGODB_URI'] %>"
      options:
        server_selection_timeout: 5

test:
  clients:
    default:
      database: hello_rails_test
      hosts:
        - localhost:27017
      options:
        user: 'testAcctUT'
        password: 'testAcctUT'
        direct_connection: true
